version: 2
jobs:
  build:
    docker:
      -image: circleci/python 3.6.1
    
    working_directory: ~/repo
    
    steps:
      -checkout
      
      -restore_cache
         keys:
           
           -v1-depedencies-{{ checksum "requirements.txt" }}
           
           -v1-depedencies-
           
           
      -run:
         name:install depedencies
         command: |
           python3 -m venv venv
           . venv/bin/activate
           make install
           
      -save_cache
         paths:
           - ./venv
         key: v1-depedencies-{{ checksum "requirements.txt" }}
         
         
      -run:
         name:run lint
         command: |
         . venv/bin/activate
         make lint
        